### ISSUE TITLE
Add multiple feature sets

### ISSUE THREAD

**Issue by parched** [parched/runtime-target-feature-rs#1]
Currently only one runtime feature set is allowed but the user should be able to add as many as they want.
Should each feature set be listed in the one attribute (delimited by `;` or similar) or should each feature set use a different attribute?

**Comment by pedrocr** [comment]
Note that it should be possible to do architecture+feature combinations.

**Comment by parched** [comment]
Done, feature sets are delimited by `;` and are selected with preference that matches the order they are declared. See https://github.com/parched/runtime-target-feature-rs/blob/603c93ae799c88a7098b699c4d0a0284171dc497/tests/src/lib.rs#L44
